In [9]:
import pandas as pd

In [13]:
df = pd.read_csv('../Dataset/new_documents.csv')

In [14]:
print(df.shape, '\n')
df.head()

(0, 10)

Empty DataFrame
Columns: [title, text, url, authors, timestamp, tags, text_length, title_length, num_tags, num_authors]
Index: []

In [12]:
# df.iloc[0:0].to_csv('../Dataset/new_documents.csv', index=False)

In [43]:
title = 'xxxxxxxxxxx'
text = 'lksdajf jlksajf s jlasj f;llj kjsdal;jf sdljkk sssssssssssssssssssssssssss'
url = 'No url'
authors = "['Abdul Rehman', 'Tahir']"
timestamp = '2020-07-01 00:00:00'
tags = "['Test', 'Sample']"

text_length = len(text.split())
title_length = len(title.split())
num_tags = len(eval(tags))
num_authors = len(eval(authors))

print(f'Text Length: {text_length}\nTitle Length: {title_length}\nNumber of Tags: {num_tags}\nNumber of Authors: {num_authors}')

Text Length: 8
Title Length: 1
Number of Tags: 2
Number of Authors: 2

In [44]:
data = {
    'title': [title],
    'text': [text],
    'url': [url],
    'authors': [authors],
    'timestamp': [timestamp],
    'tags': [tags],
    'text_length': [text_length],
    'title_length': [title_length],
    'num_tags': [num_tags],
    'num_authors': [num_authors]
}

In [45]:
df_new_doc = pd.DataFrame(data)
df = pd.concat([df, df_new_doc], ignore_index=True)

In [46]:
df.head()

,title,text,url,authors,timestamp,tags,text_length,title_length,num_tags,num_authors
0,ML is the future,Machine learning is the future of technology. ...,No url,"['Abdul Rehman', 'Tahir']",2020-07-01 00:00:00,"['ML', 'AI', 'Technology']",33,4,3,2
1,Abdul Rehman Article,This is a sample article written by Abdul Rehm...,No url,"['Abdul Rehman', 'Tahir']",2020-07-01 00:00:00,"['Test', 'Sample']",10,3,2,2
2,xxxxxxxxxxx,lksdajf jlksajf s jlasj f;llj kjsdal;jf sdljkk...,No url,"['Abdul Rehman', 'Tahir']",2020-07-01 00:00:00,"['Test', 'Sample']",8,1,2,2

In [47]:
# Saving this in the same file
df.to_csv('../Dataset/new_documents.csv', index=False)
print('New Document Added Successfully!')

New Document Added Successfully!

<hr>